#!/bin/sh

python build_image.py aperture_logo.gif
python build_image.py progress_bar.gif
python build_image.py error.gif
python build_image.py wifi_64px.gif

python build_image.py cube_dispenser_on.gif
python build_image.py cube_dispenser_off.gif
python build_image.py cube_hazard_on.gif
python build_image.py cube_hazard_off.gif
python build_image.py pellet_hazard_on.gif
python build_image.py pellet_hazard_off.gif
python build_image.py pellet_catcher_on.gif
python build_image.py pellet_catcher_off.gif
python build_image.py water_hazard_on.gif
python build_image.py water_hazard_off.gif
python build_image.py fling_enter_on.gif
python build_image.py fling_enter_off.gif
python build_image.py fling_exit_on.gif
python build_image.py fling_exit_off.gif
python build_image.py turret_hazard_on.gif
python build_image.py turret_hazard_off.gif
python build_image.py dirty_water_on.gif
python build_image.py dirty_water_off.gif
python build_image.py cake_on.gif
python build_image.py cake_off.gif
python build_image.py bridge_shield_on.gif
python build_image.py bridge_shield_off.gif
python build_image.py cube_button_on.gif
python build_image.py cube_button_off.gif
python build_image.py faith_plate_on.gif
python build_image.py faith_plate_off.gif
python build_image.py laser_hazard_on.gif
python build_image.py laser_hazard_off.gif
python build_image.py laser_redirection_on.gif
python build_image.py laser_redirection_off.gif
python build_image.py laser_sensor_on.gif
python build_image.py laser_sensor_off.gif
python build_image.py light_bridge_on.gif
python build_image.py light_bridge_off.gif
python build_image.py player_button_on.gif
python build_image.py player_button_off.gif

python build_image.py weather_info_degree_symbol.gif
python build_image.py weather_info_percent_symbol.gif
python build_image.py weather_frame.gif
python build_image.py weather_frame_empty.gif
python build_image.py weather_cloudy.gif
python build_image.py weather_fog.gif
python build_image.py weather_thunderstorms.gif
python build_image.py weather_showers.gif
python build_image.py weather_snow.gif
python build_image.py weather_day_clear.gif
python build_image.py weather_night_clear.gif
python build_image.py weather_partly_cloudy_day.gif
python build_image.py weather_partly_cloudy_night.gif
python build_image.py weather_scattered_showers_day.gif
python build_image.py weather_scattered_showers_night.gif
