python build_image.py aperture_logo.gif
python build_image.py progress_bar.gif
python build_image.py error.gif

python build_image.py cube_dispenser_on.gif
python build_image.py cube_dispenser_off.gif
python build_image.py cube_hazard_on.gif
python build_image.py cube_hazard_off.gif
python build_image.py pellet_hazard_on.gif
python build_image.py pellet_hazard_off.gif
python build_image.py pellet_catcher_on.gif
python build_image.py pellet_catcher_off.gif
python build_image.py water_hazard_on.gif
python build_image.py water_hazard_off.gif
python build_image.py fling_enter_on.gif
python build_image.py fling_enter_off.gif
python build_image.py fling_exit_on.gif
python build_image.py fling_exit_off.gif
python build_image.py turret_hazard_on.gif
python build_image.py turret_hazard_off.gif
python build_image.py dirty_water_on.gif
python build_image.py dirty_water_off.gif
python build_image.py cake_on.gif
python build_image.py cake_off.gif
